[window]
decorations="None"
startup_mode="Fullscreen"
[font]
normal = { family = "EnvyCodeR Nerd Font Mono", style = "Regular"}
bold = { style = "Bold" }
italic = { style = "Italic" }
size = 13
builtin_box_drawing = false
[cursor]
style = { blinking = "On" }
blink_interval = 600
blink_timeout = 0
unfocused_hollow = true
