
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_DATA_DIRS="$XDG_DATA_DIRS:/usr/local/share:/usr/share:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share"
export ZDOTDIR=$XDG_CONFIG_HOME/shell/zsh
export HISTFILE=$XDG_CONFIG_HOME/shell/.histfile
export PATH=$PATH":/usr/local/go/bin:$HOME/go/bin"

